package com.william.mapper;

import com.william.model.OrderProduct;
import com.william.model.OrderProductExample;
import com.william.model.OrderProductKey;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface OrderProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_order
     *
     * @mbggenerated Sat Mar 18 23:41:51 CST 2017
     */
    @SelectProvider(type=OrderProductSqlProvider.class, method="countByExample")
    int countByExample(OrderProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_order
     *
     * @mbggenerated Sat Mar 18 23:41:51 CST 2017
     */
    @DeleteProvider(type=OrderProductSqlProvider.class, method="deleteByExample")
    int deleteByExample(OrderProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_order
     *
     * @mbggenerated Sat Mar 18 23:41:51 CST 2017
     */
    @Delete({
        "delete from product_order",
        "where order_id = #{orderId,jdbcType=INTEGER}",
          "and product_id = #{productId,jdbcType=INTEGER}",
          "and warehouse_id = #{warehouseId,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(OrderProductKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_order
     *
     * @mbggenerated Sat Mar 18 23:41:51 CST 2017
     */
    @Insert({
        "insert into product_order (order_id, product_id, ",
        "warehouse_id, quantity, ",
        "price, isnew)",
        "values (#{orderId,jdbcType=INTEGER}, #{productId,jdbcType=INTEGER}, ",
        "#{warehouseId,jdbcType=INTEGER}, #{quantity,jdbcType=INTEGER}, ",
        "#{price,jdbcType=DECIMAL}, #{isnew,jdbcType=SMALLINT})"
    })
    int insert(OrderProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_order
     *
     * @mbggenerated Sat Mar 18 23:41:51 CST 2017
     */
    @InsertProvider(type=OrderProductSqlProvider.class, method="insertSelective")
    int insertSelective(OrderProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_order
     *
     * @mbggenerated Sat Mar 18 23:41:51 CST 2017
     */
    @SelectProvider(type=OrderProductSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="order_id", property="orderId", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="product_id", property="productId", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="warehouse_id", property="warehouseId", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="quantity", property="quantity", jdbcType=JdbcType.INTEGER),
        @Result(column="price", property="price", jdbcType=JdbcType.DECIMAL),
        @Result(column="isnew", property="isnew", jdbcType=JdbcType.SMALLINT)
    })
    List<OrderProduct> selectByExample(OrderProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_order
     *
     * @mbggenerated Sat Mar 18 23:41:51 CST 2017
     */
    @Select({
        "select",
        "order_id, product_id, warehouse_id, quantity, price, isnew",
        "from product_order",
        "where order_id = #{orderId,jdbcType=INTEGER}",
          "and product_id = #{productId,jdbcType=INTEGER}",
          "and warehouse_id = #{warehouseId,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="order_id", property="orderId", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="product_id", property="productId", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="warehouse_id", property="warehouseId", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="quantity", property="quantity", jdbcType=JdbcType.INTEGER),
        @Result(column="price", property="price", jdbcType=JdbcType.DECIMAL),
        @Result(column="isnew", property="isnew", jdbcType=JdbcType.SMALLINT)
    })
    OrderProduct selectByPrimaryKey(OrderProductKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_order
     *
     * @mbggenerated Sat Mar 18 23:41:51 CST 2017
     */
    @UpdateProvider(type=OrderProductSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") OrderProduct record, @Param("example") OrderProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_order
     *
     * @mbggenerated Sat Mar 18 23:41:51 CST 2017
     */
    @UpdateProvider(type=OrderProductSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") OrderProduct record, @Param("example") OrderProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_order
     *
     * @mbggenerated Sat Mar 18 23:41:51 CST 2017
     */
    @UpdateProvider(type=OrderProductSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(OrderProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_order
     *
     * @mbggenerated Sat Mar 18 23:41:51 CST 2017
     */
    @Update({
        "update product_order",
        "set quantity = #{quantity,jdbcType=INTEGER},",
          "price = #{price,jdbcType=DECIMAL},",
          "isnew = #{isnew,jdbcType=SMALLINT}",
        "where order_id = #{orderId,jdbcType=INTEGER}",
          "and product_id = #{productId,jdbcType=INTEGER}",
          "and warehouse_id = #{warehouseId,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(OrderProduct record);
}