package com.william.mapper;

import com.william.model.Product;
import com.william.model.ProductExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface ProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table products
     *
     * @mbggenerated Sat Mar 18 23:41:51 CST 2017
     */
    @SelectProvider(type=ProductSqlProvider.class, method="countByExample")
    int countByExample(ProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table products
     *
     * @mbggenerated Sat Mar 18 23:41:51 CST 2017
     */
    @DeleteProvider(type=ProductSqlProvider.class, method="deleteByExample")
    int deleteByExample(ProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table products
     *
     * @mbggenerated Sat Mar 18 23:41:51 CST 2017
     */
    @Delete({
        "delete from products",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table products
     *
     * @mbggenerated Sat Mar 18 23:41:51 CST 2017
     */
    @Insert({
        "insert into products (id, category_id, ",
        "isbn, name, photo, ",
        "publisher, price, ",
        "original_price, author, ",
        "points, minimum, ",
        "sort_order, substract, ",
        "status, sold, month_sold, ",
        "store_id, created_at, ",
        "updated_at, deleted_at)",
        "values (#{id,jdbcType=INTEGER}, #{categoryId,jdbcType=INTEGER}, ",
        "#{isbn,jdbcType=CHAR}, #{name,jdbcType=VARCHAR}, #{photo,jdbcType=VARCHAR}, ",
        "#{publisher,jdbcType=VARCHAR}, #{price,jdbcType=DECIMAL}, ",
        "#{originalPrice,jdbcType=DECIMAL}, #{author,jdbcType=VARCHAR}, ",
        "#{points,jdbcType=INTEGER}, #{minimum,jdbcType=SMALLINT}, ",
        "#{sortOrder,jdbcType=INTEGER}, #{substract,jdbcType=TINYINT}, ",
        "#{status,jdbcType=TINYINT}, #{sold,jdbcType=INTEGER}, #{monthSold,jdbcType=INTEGER}, ",
        "#{storeId,jdbcType=INTEGER}, #{createdAt,jdbcType=TIMESTAMP}, ",
        "#{updatedAt,jdbcType=TIMESTAMP}, #{deletedAt,jdbcType=TIMESTAMP})"
    })
    int insert(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table products
     *
     * @mbggenerated Sat Mar 18 23:41:51 CST 2017
     */
    @InsertProvider(type=ProductSqlProvider.class, method="insertSelective")
    int insertSelective(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table products
     *
     * @mbggenerated Sat Mar 18 23:41:51 CST 2017
     */
    @SelectProvider(type=ProductSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="category_id", property="categoryId", jdbcType=JdbcType.INTEGER),
        @Result(column="isbn", property="isbn", jdbcType=JdbcType.CHAR),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="photo", property="photo", jdbcType=JdbcType.VARCHAR),
        @Result(column="publisher", property="publisher", jdbcType=JdbcType.VARCHAR),
        @Result(column="price", property="price", jdbcType=JdbcType.DECIMAL),
        @Result(column="original_price", property="originalPrice", jdbcType=JdbcType.DECIMAL),
        @Result(column="author", property="author", jdbcType=JdbcType.VARCHAR),
        @Result(column="points", property="points", jdbcType=JdbcType.INTEGER),
        @Result(column="minimum", property="minimum", jdbcType=JdbcType.SMALLINT),
        @Result(column="sort_order", property="sortOrder", jdbcType=JdbcType.INTEGER),
        @Result(column="substract", property="substract", jdbcType=JdbcType.TINYINT),
        @Result(column="status", property="status", jdbcType=JdbcType.TINYINT),
        @Result(column="sold", property="sold", jdbcType=JdbcType.INTEGER),
        @Result(column="month_sold", property="monthSold", jdbcType=JdbcType.INTEGER),
        @Result(column="store_id", property="storeId", jdbcType=JdbcType.INTEGER),
        @Result(column="created_at", property="createdAt", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="updated_at", property="updatedAt", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="deleted_at", property="deletedAt", jdbcType=JdbcType.TIMESTAMP)
    })
    List<Product> selectByExample(ProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table products
     *
     * @mbggenerated Sat Mar 18 23:41:51 CST 2017
     */
    @Select({
        "select",
        "id, category_id, isbn, name, photo, publisher, price, original_price, author, ",
        "points, minimum, sort_order, substract, status, sold, month_sold, store_id, ",
        "created_at, updated_at, deleted_at",
        "from products",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="category_id", property="categoryId", jdbcType=JdbcType.INTEGER),
        @Result(column="isbn", property="isbn", jdbcType=JdbcType.CHAR),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="photo", property="photo", jdbcType=JdbcType.VARCHAR),
        @Result(column="publisher", property="publisher", jdbcType=JdbcType.VARCHAR),
        @Result(column="price", property="price", jdbcType=JdbcType.DECIMAL),
        @Result(column="original_price", property="originalPrice", jdbcType=JdbcType.DECIMAL),
        @Result(column="author", property="author", jdbcType=JdbcType.VARCHAR),
        @Result(column="points", property="points", jdbcType=JdbcType.INTEGER),
        @Result(column="minimum", property="minimum", jdbcType=JdbcType.SMALLINT),
        @Result(column="sort_order", property="sortOrder", jdbcType=JdbcType.INTEGER),
        @Result(column="substract", property="substract", jdbcType=JdbcType.TINYINT),
        @Result(column="status", property="status", jdbcType=JdbcType.TINYINT),
        @Result(column="sold", property="sold", jdbcType=JdbcType.INTEGER),
        @Result(column="month_sold", property="monthSold", jdbcType=JdbcType.INTEGER),
        @Result(column="store_id", property="storeId", jdbcType=JdbcType.INTEGER),
        @Result(column="created_at", property="createdAt", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="updated_at", property="updatedAt", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="deleted_at", property="deletedAt", jdbcType=JdbcType.TIMESTAMP)
    })
    Product selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table products
     *
     * @mbggenerated Sat Mar 18 23:41:51 CST 2017
     */
    @UpdateProvider(type=ProductSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") Product record, @Param("example") ProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table products
     *
     * @mbggenerated Sat Mar 18 23:41:51 CST 2017
     */
    @UpdateProvider(type=ProductSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") Product record, @Param("example") ProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table products
     *
     * @mbggenerated Sat Mar 18 23:41:51 CST 2017
     */
    @UpdateProvider(type=ProductSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table products
     *
     * @mbggenerated Sat Mar 18 23:41:51 CST 2017
     */
    @Update({
        "update products",
        "set category_id = #{categoryId,jdbcType=INTEGER},",
          "isbn = #{isbn,jdbcType=CHAR},",
          "name = #{name,jdbcType=VARCHAR},",
          "photo = #{photo,jdbcType=VARCHAR},",
          "publisher = #{publisher,jdbcType=VARCHAR},",
          "price = #{price,jdbcType=DECIMAL},",
          "original_price = #{originalPrice,jdbcType=DECIMAL},",
          "author = #{author,jdbcType=VARCHAR},",
          "points = #{points,jdbcType=INTEGER},",
          "minimum = #{minimum,jdbcType=SMALLINT},",
          "sort_order = #{sortOrder,jdbcType=INTEGER},",
          "substract = #{substract,jdbcType=TINYINT},",
          "status = #{status,jdbcType=TINYINT},",
          "sold = #{sold,jdbcType=INTEGER},",
          "month_sold = #{monthSold,jdbcType=INTEGER},",
          "store_id = #{storeId,jdbcType=INTEGER},",
          "created_at = #{createdAt,jdbcType=TIMESTAMP},",
          "updated_at = #{updatedAt,jdbcType=TIMESTAMP},",
          "deleted_at = #{deletedAt,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Product record);
}