package com.william.model;

public class Category {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column categories.id
     *
     * @mbggenerated Fri Mar 17 15:26:19 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column categories.parent_id
     *
     * @mbggenerated Fri Mar 17 15:26:19 CST 2017
     */
    private Integer parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column categories.name
     *
     * @mbggenerated Fri Mar 17 15:26:19 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column categories.sort_order
     *
     * @mbggenerated Fri Mar 17 15:26:19 CST 2017
     */
    private Integer sortOrder;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column categories.id
     *
     * @return the value of categories.id
     *
     * @mbggenerated Fri Mar 17 15:26:19 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column categories.id
     *
     * @param id the value for categories.id
     *
     * @mbggenerated Fri Mar 17 15:26:19 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column categories.parent_id
     *
     * @return the value of categories.parent_id
     *
     * @mbggenerated Fri Mar 17 15:26:19 CST 2017
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column categories.parent_id
     *
     * @param parentId the value for categories.parent_id
     *
     * @mbggenerated Fri Mar 17 15:26:19 CST 2017
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column categories.name
     *
     * @return the value of categories.name
     *
     * @mbggenerated Fri Mar 17 15:26:19 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column categories.name
     *
     * @param name the value for categories.name
     *
     * @mbggenerated Fri Mar 17 15:26:19 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column categories.sort_order
     *
     * @return the value of categories.sort_order
     *
     * @mbggenerated Fri Mar 17 15:26:19 CST 2017
     */
    public Integer getSortOrder() {
        return sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column categories.sort_order
     *
     * @param sortOrder the value for categories.sort_order
     *
     * @mbggenerated Fri Mar 17 15:26:19 CST 2017
     */
    public void setSortOrder(Integer sortOrder) {
        this.sortOrder = sortOrder;
    }
}