package com.william.model;

public class OrderProductKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_order.order_id
     *
     * @mbggenerated Sat Mar 18 23:41:51 CST 2017
     */
    private Integer orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_order.product_id
     *
     * @mbggenerated Sat Mar 18 23:41:51 CST 2017
     */
    private Integer productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_order.warehouse_id
     *
     * @mbggenerated Sat Mar 18 23:41:51 CST 2017
     */
    private Integer warehouseId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_order.order_id
     *
     * @return the value of product_order.order_id
     *
     * @mbggenerated Sat Mar 18 23:41:51 CST 2017
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_order.order_id
     *
     * @param orderId the value for product_order.order_id
     *
     * @mbggenerated Sat Mar 18 23:41:51 CST 2017
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_order.product_id
     *
     * @return the value of product_order.product_id
     *
     * @mbggenerated Sat Mar 18 23:41:51 CST 2017
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_order.product_id
     *
     * @param productId the value for product_order.product_id
     *
     * @mbggenerated Sat Mar 18 23:41:51 CST 2017
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_order.warehouse_id
     *
     * @return the value of product_order.warehouse_id
     *
     * @mbggenerated Sat Mar 18 23:41:51 CST 2017
     */
    public Integer getWarehouseId() {
        return warehouseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_order.warehouse_id
     *
     * @param warehouseId the value for product_order.warehouse_id
     *
     * @mbggenerated Sat Mar 18 23:41:51 CST 2017
     */
    public void setWarehouseId(Integer warehouseId) {
        this.warehouseId = warehouseId;
    }
}