package com.william.model;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

public class Order {

    public List<Product> getProducts() {
        return products;
    }

    public void setProducts(List<Product> products) {
        this.products = products;
    }

    List<Product> products;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.id
     *
     * @mbggenerated Sat Mar 18 23:41:51 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.mode
     *
     * @mbggenerated Sat Mar 18 23:41:51 CST 2017
     */
    private Short mode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.store_name
     *
     * @mbggenerated Sat Mar 18 23:41:51 CST 2017
     */
    private String storeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.user_name
     *
     * @mbggenerated Sat Mar 18 23:41:51 CST 2017
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.total
     *
     * @mbggenerated Sat Mar 18 23:41:51 CST 2017
     */
    private BigDecimal total;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.discount
     *
     * @mbggenerated Sat Mar 18 23:41:51 CST 2017
     */
    private BigDecimal discount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.actual_pay_foregift
     *
     * @mbggenerated Sat Mar 18 23:41:51 CST 2017
     */
    private BigDecimal actualPayForegift;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.foregift
     *
     * @mbggenerated Sat Mar 18 23:41:51 CST 2017
     */
    private BigDecimal foregift;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.coupon_id
     *
     * @mbggenerated Sat Mar 18 23:41:51 CST 2017
     */
    private Integer couponId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.pay_amount
     *
     * @mbggenerated Sat Mar 18 23:41:51 CST 2017
     */
    private BigDecimal payAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.phone
     *
     * @mbggenerated Sat Mar 18 23:41:51 CST 2017
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.user_id
     *
     * @mbggenerated Sat Mar 18 23:41:51 CST 2017
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.store_id
     *
     * @mbggenerated Sat Mar 18 23:41:51 CST 2017
     */
    private Integer storeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.order_status_id
     *
     * @mbggenerated Sat Mar 18 23:41:51 CST 2017
     */
    private Integer orderStatusId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.payment_id
     *
     * @mbggenerated Sat Mar 18 23:41:51 CST 2017
     */
    private Integer paymentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.payment_name
     *
     * @mbggenerated Sat Mar 18 23:41:51 CST 2017
     */
    private String paymentName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.actual_pay_amount
     *
     * @mbggenerated Sat Mar 18 23:41:51 CST 2017
     */
    private BigDecimal actualPayAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.shipping_id
     *
     * @mbggenerated Sat Mar 18 23:41:51 CST 2017
     */
    private Integer shippingId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.shipping_name
     *
     * @mbggenerated Sat Mar 18 23:41:51 CST 2017
     */
    private String shippingName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.school_id
     *
     * @mbggenerated Sat Mar 18 23:41:51 CST 2017
     */
    private Integer schoolId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.school_name
     *
     * @mbggenerated Sat Mar 18 23:41:51 CST 2017
     */
    private String schoolName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.province
     *
     * @mbggenerated Sat Mar 18 23:41:51 CST 2017
     */
    private Integer province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.province_name
     *
     * @mbggenerated Sat Mar 18 23:41:51 CST 2017
     */
    private String provinceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.city
     *
     * @mbggenerated Sat Mar 18 23:41:51 CST 2017
     */
    private Integer city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.city_name
     *
     * @mbggenerated Sat Mar 18 23:41:51 CST 2017
     */
    private String cityName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.district
     *
     * @mbggenerated Sat Mar 18 23:41:51 CST 2017
     */
    private Integer district;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.district_name
     *
     * @mbggenerated Sat Mar 18 23:41:51 CST 2017
     */
    private String districtName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.address
     *
     * @mbggenerated Sat Mar 18 23:41:51 CST 2017
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.postcode
     *
     * @mbggenerated Sat Mar 18 23:41:51 CST 2017
     */
    private String postcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.ip
     *
     * @mbggenerated Sat Mar 18 23:41:51 CST 2017
     */
    private String ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.created_at
     *
     * @mbggenerated Sat Mar 18 23:41:51 CST 2017
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.updated_at
     *
     * @mbggenerated Sat Mar 18 23:41:51 CST 2017
     */
    private Date updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.deleted_at
     *
     * @mbggenerated Sat Mar 18 23:41:51 CST 2017
     */
    private Date deletedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.ispaid
     *
     * @mbggenerated Sat Mar 18 23:41:51 CST 2017
     */
    private Byte ispaid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.shipping_amount
     *
     * @mbggenerated Sat Mar 18 23:41:51 CST 2017
     */
    private BigDecimal shippingAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.express_number
     *
     * @mbggenerated Sat Mar 18 23:41:51 CST 2017
     */
    private String expressNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.reservation_pay_time
     *
     * @mbggenerated Sat Mar 18 23:41:51 CST 2017
     */
    private Date reservationPayTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.id
     *
     * @return the value of orders.id
     *
     * @mbggenerated Sat Mar 18 23:41:51 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.id
     *
     * @param id the value for orders.id
     *
     * @mbggenerated Sat Mar 18 23:41:51 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.mode
     *
     * @return the value of orders.mode
     *
     * @mbggenerated Sat Mar 18 23:41:51 CST 2017
     */
    public Short getMode() {
        return mode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.mode
     *
     * @param mode the value for orders.mode
     *
     * @mbggenerated Sat Mar 18 23:41:51 CST 2017
     */
    public void setMode(Short mode) {
        this.mode = mode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.store_name
     *
     * @return the value of orders.store_name
     *
     * @mbggenerated Sat Mar 18 23:41:51 CST 2017
     */
    public String getStoreName() {
        return storeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.store_name
     *
     * @param storeName the value for orders.store_name
     *
     * @mbggenerated Sat Mar 18 23:41:51 CST 2017
     */
    public void setStoreName(String storeName) {
        this.storeName = storeName == null ? null : storeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.user_name
     *
     * @return the value of orders.user_name
     *
     * @mbggenerated Sat Mar 18 23:41:51 CST 2017
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.user_name
     *
     * @param userName the value for orders.user_name
     *
     * @mbggenerated Sat Mar 18 23:41:51 CST 2017
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.total
     *
     * @return the value of orders.total
     *
     * @mbggenerated Sat Mar 18 23:41:51 CST 2017
     */
    public BigDecimal getTotal() {
        return total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.total
     *
     * @param total the value for orders.total
     *
     * @mbggenerated Sat Mar 18 23:41:51 CST 2017
     */
    public void setTotal(BigDecimal total) {
        this.total = total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.discount
     *
     * @return the value of orders.discount
     *
     * @mbggenerated Sat Mar 18 23:41:51 CST 2017
     */
    public BigDecimal getDiscount() {
        return discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.discount
     *
     * @param discount the value for orders.discount
     *
     * @mbggenerated Sat Mar 18 23:41:51 CST 2017
     */
    public void setDiscount(BigDecimal discount) {
        this.discount = discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.actual_pay_foregift
     *
     * @return the value of orders.actual_pay_foregift
     *
     * @mbggenerated Sat Mar 18 23:41:51 CST 2017
     */
    public BigDecimal getActualPayForegift() {
        return actualPayForegift;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.actual_pay_foregift
     *
     * @param actualPayForegift the value for orders.actual_pay_foregift
     *
     * @mbggenerated Sat Mar 18 23:41:51 CST 2017
     */
    public void setActualPayForegift(BigDecimal actualPayForegift) {
        this.actualPayForegift = actualPayForegift;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.foregift
     *
     * @return the value of orders.foregift
     *
     * @mbggenerated Sat Mar 18 23:41:51 CST 2017
     */
    public BigDecimal getForegift() {
        return foregift;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.foregift
     *
     * @param foregift the value for orders.foregift
     *
     * @mbggenerated Sat Mar 18 23:41:51 CST 2017
     */
    public void setForegift(BigDecimal foregift) {
        this.foregift = foregift;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.coupon_id
     *
     * @return the value of orders.coupon_id
     *
     * @mbggenerated Sat Mar 18 23:41:51 CST 2017
     */
    public Integer getCouponId() {
        return couponId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.coupon_id
     *
     * @param couponId the value for orders.coupon_id
     *
     * @mbggenerated Sat Mar 18 23:41:51 CST 2017
     */
    public void setCouponId(Integer couponId) {
        this.couponId = couponId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.pay_amount
     *
     * @return the value of orders.pay_amount
     *
     * @mbggenerated Sat Mar 18 23:41:51 CST 2017
     */
    public BigDecimal getPayAmount() {
        return payAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.pay_amount
     *
     * @param payAmount the value for orders.pay_amount
     *
     * @mbggenerated Sat Mar 18 23:41:51 CST 2017
     */
    public void setPayAmount(BigDecimal payAmount) {
        this.payAmount = payAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.phone
     *
     * @return the value of orders.phone
     *
     * @mbggenerated Sat Mar 18 23:41:51 CST 2017
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.phone
     *
     * @param phone the value for orders.phone
     *
     * @mbggenerated Sat Mar 18 23:41:51 CST 2017
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.user_id
     *
     * @return the value of orders.user_id
     *
     * @mbggenerated Sat Mar 18 23:41:51 CST 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.user_id
     *
     * @param userId the value for orders.user_id
     *
     * @mbggenerated Sat Mar 18 23:41:51 CST 2017
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.store_id
     *
     * @return the value of orders.store_id
     *
     * @mbggenerated Sat Mar 18 23:41:51 CST 2017
     */
    public Integer getStoreId() {
        return storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.store_id
     *
     * @param storeId the value for orders.store_id
     *
     * @mbggenerated Sat Mar 18 23:41:51 CST 2017
     */
    public void setStoreId(Integer storeId) {
        this.storeId = storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.order_status_id
     *
     * @return the value of orders.order_status_id
     *
     * @mbggenerated Sat Mar 18 23:41:51 CST 2017
     */
    public Integer getOrderStatusId() {
        return orderStatusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.order_status_id
     *
     * @param orderStatusId the value for orders.order_status_id
     *
     * @mbggenerated Sat Mar 18 23:41:51 CST 2017
     */
    public void setOrderStatusId(Integer orderStatusId) {
        this.orderStatusId = orderStatusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.payment_id
     *
     * @return the value of orders.payment_id
     *
     * @mbggenerated Sat Mar 18 23:41:51 CST 2017
     */
    public Integer getPaymentId() {
        return paymentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.payment_id
     *
     * @param paymentId the value for orders.payment_id
     *
     * @mbggenerated Sat Mar 18 23:41:51 CST 2017
     */
    public void setPaymentId(Integer paymentId) {
        this.paymentId = paymentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.payment_name
     *
     * @return the value of orders.payment_name
     *
     * @mbggenerated Sat Mar 18 23:41:51 CST 2017
     */
    public String getPaymentName() {
        return paymentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.payment_name
     *
     * @param paymentName the value for orders.payment_name
     *
     * @mbggenerated Sat Mar 18 23:41:51 CST 2017
     */
    public void setPaymentName(String paymentName) {
        this.paymentName = paymentName == null ? null : paymentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.actual_pay_amount
     *
     * @return the value of orders.actual_pay_amount
     *
     * @mbggenerated Sat Mar 18 23:41:51 CST 2017
     */
    public BigDecimal getActualPayAmount() {
        return actualPayAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.actual_pay_amount
     *
     * @param actualPayAmount the value for orders.actual_pay_amount
     *
     * @mbggenerated Sat Mar 18 23:41:51 CST 2017
     */
    public void setActualPayAmount(BigDecimal actualPayAmount) {
        this.actualPayAmount = actualPayAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.shipping_id
     *
     * @return the value of orders.shipping_id
     *
     * @mbggenerated Sat Mar 18 23:41:51 CST 2017
     */
    public Integer getShippingId() {
        return shippingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.shipping_id
     *
     * @param shippingId the value for orders.shipping_id
     *
     * @mbggenerated Sat Mar 18 23:41:51 CST 2017
     */
    public void setShippingId(Integer shippingId) {
        this.shippingId = shippingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.shipping_name
     *
     * @return the value of orders.shipping_name
     *
     * @mbggenerated Sat Mar 18 23:41:51 CST 2017
     */
    public String getShippingName() {
        return shippingName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.shipping_name
     *
     * @param shippingName the value for orders.shipping_name
     *
     * @mbggenerated Sat Mar 18 23:41:51 CST 2017
     */
    public void setShippingName(String shippingName) {
        this.shippingName = shippingName == null ? null : shippingName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.school_id
     *
     * @return the value of orders.school_id
     *
     * @mbggenerated Sat Mar 18 23:41:51 CST 2017
     */
    public Integer getSchoolId() {
        return schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.school_id
     *
     * @param schoolId the value for orders.school_id
     *
     * @mbggenerated Sat Mar 18 23:41:51 CST 2017
     */
    public void setSchoolId(Integer schoolId) {
        this.schoolId = schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.school_name
     *
     * @return the value of orders.school_name
     *
     * @mbggenerated Sat Mar 18 23:41:51 CST 2017
     */
    public String getSchoolName() {
        return schoolName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.school_name
     *
     * @param schoolName the value for orders.school_name
     *
     * @mbggenerated Sat Mar 18 23:41:51 CST 2017
     */
    public void setSchoolName(String schoolName) {
        this.schoolName = schoolName == null ? null : schoolName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.province
     *
     * @return the value of orders.province
     *
     * @mbggenerated Sat Mar 18 23:41:51 CST 2017
     */
    public Integer getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.province
     *
     * @param province the value for orders.province
     *
     * @mbggenerated Sat Mar 18 23:41:51 CST 2017
     */
    public void setProvince(Integer province) {
        this.province = province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.province_name
     *
     * @return the value of orders.province_name
     *
     * @mbggenerated Sat Mar 18 23:41:51 CST 2017
     */
    public String getProvinceName() {
        return provinceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.province_name
     *
     * @param provinceName the value for orders.province_name
     *
     * @mbggenerated Sat Mar 18 23:41:51 CST 2017
     */
    public void setProvinceName(String provinceName) {
        this.provinceName = provinceName == null ? null : provinceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.city
     *
     * @return the value of orders.city
     *
     * @mbggenerated Sat Mar 18 23:41:51 CST 2017
     */
    public Integer getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.city
     *
     * @param city the value for orders.city
     *
     * @mbggenerated Sat Mar 18 23:41:51 CST 2017
     */
    public void setCity(Integer city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.city_name
     *
     * @return the value of orders.city_name
     *
     * @mbggenerated Sat Mar 18 23:41:51 CST 2017
     */
    public String getCityName() {
        return cityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.city_name
     *
     * @param cityName the value for orders.city_name
     *
     * @mbggenerated Sat Mar 18 23:41:51 CST 2017
     */
    public void setCityName(String cityName) {
        this.cityName = cityName == null ? null : cityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.district
     *
     * @return the value of orders.district
     *
     * @mbggenerated Sat Mar 18 23:41:51 CST 2017
     */
    public Integer getDistrict() {
        return district;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.district
     *
     * @param district the value for orders.district
     *
     * @mbggenerated Sat Mar 18 23:41:51 CST 2017
     */
    public void setDistrict(Integer district) {
        this.district = district;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.district_name
     *
     * @return the value of orders.district_name
     *
     * @mbggenerated Sat Mar 18 23:41:51 CST 2017
     */
    public String getDistrictName() {
        return districtName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.district_name
     *
     * @param districtName the value for orders.district_name
     *
     * @mbggenerated Sat Mar 18 23:41:51 CST 2017
     */
    public void setDistrictName(String districtName) {
        this.districtName = districtName == null ? null : districtName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.address
     *
     * @return the value of orders.address
     *
     * @mbggenerated Sat Mar 18 23:41:51 CST 2017
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.address
     *
     * @param address the value for orders.address
     *
     * @mbggenerated Sat Mar 18 23:41:51 CST 2017
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.postcode
     *
     * @return the value of orders.postcode
     *
     * @mbggenerated Sat Mar 18 23:41:51 CST 2017
     */
    public String getPostcode() {
        return postcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.postcode
     *
     * @param postcode the value for orders.postcode
     *
     * @mbggenerated Sat Mar 18 23:41:51 CST 2017
     */
    public void setPostcode(String postcode) {
        this.postcode = postcode == null ? null : postcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.ip
     *
     * @return the value of orders.ip
     *
     * @mbggenerated Sat Mar 18 23:41:51 CST 2017
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.ip
     *
     * @param ip the value for orders.ip
     *
     * @mbggenerated Sat Mar 18 23:41:51 CST 2017
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.created_at
     *
     * @return the value of orders.created_at
     *
     * @mbggenerated Sat Mar 18 23:41:51 CST 2017
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.created_at
     *
     * @param createdAt the value for orders.created_at
     *
     * @mbggenerated Sat Mar 18 23:41:51 CST 2017
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.updated_at
     *
     * @return the value of orders.updated_at
     *
     * @mbggenerated Sat Mar 18 23:41:51 CST 2017
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.updated_at
     *
     * @param updatedAt the value for orders.updated_at
     *
     * @mbggenerated Sat Mar 18 23:41:51 CST 2017
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.deleted_at
     *
     * @return the value of orders.deleted_at
     *
     * @mbggenerated Sat Mar 18 23:41:51 CST 2017
     */
    public Date getDeletedAt() {
        return deletedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.deleted_at
     *
     * @param deletedAt the value for orders.deleted_at
     *
     * @mbggenerated Sat Mar 18 23:41:51 CST 2017
     */
    public void setDeletedAt(Date deletedAt) {
        this.deletedAt = deletedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.ispaid
     *
     * @return the value of orders.ispaid
     *
     * @mbggenerated Sat Mar 18 23:41:51 CST 2017
     */
    public Byte getIspaid() {
        return ispaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.ispaid
     *
     * @param ispaid the value for orders.ispaid
     *
     * @mbggenerated Sat Mar 18 23:41:51 CST 2017
     */
    public void setIspaid(Byte ispaid) {
        this.ispaid = ispaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.shipping_amount
     *
     * @return the value of orders.shipping_amount
     *
     * @mbggenerated Sat Mar 18 23:41:51 CST 2017
     */
    public BigDecimal getShippingAmount() {
        return shippingAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.shipping_amount
     *
     * @param shippingAmount the value for orders.shipping_amount
     *
     * @mbggenerated Sat Mar 18 23:41:51 CST 2017
     */
    public void setShippingAmount(BigDecimal shippingAmount) {
        this.shippingAmount = shippingAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.express_number
     *
     * @return the value of orders.express_number
     *
     * @mbggenerated Sat Mar 18 23:41:51 CST 2017
     */
    public String getExpressNumber() {
        return expressNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.express_number
     *
     * @param expressNumber the value for orders.express_number
     *
     * @mbggenerated Sat Mar 18 23:41:51 CST 2017
     */
    public void setExpressNumber(String expressNumber) {
        this.expressNumber = expressNumber == null ? null : expressNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.reservation_pay_time
     *
     * @return the value of orders.reservation_pay_time
     *
     * @mbggenerated Sat Mar 18 23:41:51 CST 2017
     */
    public Date getReservationPayTime() {
        return reservationPayTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.reservation_pay_time
     *
     * @param reservationPayTime the value for orders.reservation_pay_time
     *
     * @mbggenerated Sat Mar 18 23:41:51 CST 2017
     */
    public void setReservationPayTime(Date reservationPayTime) {
        this.reservationPayTime = reservationPayTime;
    }
}