package com.william.model;

import java.math.BigDecimal;
import java.util.Date;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.id
     *
     * @mbggenerated Fri Mar 17 15:26:18 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.user_name
     *
     * @mbggenerated Fri Mar 17 15:26:18 CST 2017
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.balance
     *
     * @mbggenerated Fri Mar 17 15:26:18 CST 2017
     */
    private BigDecimal balance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.password
     *
     * @mbggenerated Fri Mar 17 15:26:18 CST 2017
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.phone
     *
     * @mbggenerated Fri Mar 17 15:26:18 CST 2017
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.email
     *
     * @mbggenerated Fri Mar 17 15:26:18 CST 2017
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.school_id
     *
     * @mbggenerated Fri Mar 17 15:26:18 CST 2017
     */
    private Integer schoolId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.default_addr_id
     *
     * @mbggenerated Fri Mar 17 15:26:18 CST 2017
     */
    private Integer defaultAddrId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.openid
     *
     * @mbggenerated Fri Mar 17 15:26:18 CST 2017
     */
    private String openid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.photo
     *
     * @mbggenerated Fri Mar 17 15:26:18 CST 2017
     */
    private String photo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.points
     *
     * @mbggenerated Fri Mar 17 15:26:18 CST 2017
     */
    private Integer points;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.created_at
     *
     * @mbggenerated Fri Mar 17 15:26:18 CST 2017
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.updated_at
     *
     * @mbggenerated Fri Mar 17 15:26:18 CST 2017
     */
    private Date updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.deleted_at
     *
     * @mbggenerated Fri Mar 17 15:26:18 CST 2017
     */
    private Date deletedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.id
     *
     * @return the value of users.id
     *
     * @mbggenerated Fri Mar 17 15:26:18 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.id
     *
     * @param id the value for users.id
     *
     * @mbggenerated Fri Mar 17 15:26:18 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.user_name
     *
     * @return the value of users.user_name
     *
     * @mbggenerated Fri Mar 17 15:26:18 CST 2017
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.user_name
     *
     * @param userName the value for users.user_name
     *
     * @mbggenerated Fri Mar 17 15:26:18 CST 2017
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.balance
     *
     * @return the value of users.balance
     *
     * @mbggenerated Fri Mar 17 15:26:18 CST 2017
     */
    public BigDecimal getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.balance
     *
     * @param balance the value for users.balance
     *
     * @mbggenerated Fri Mar 17 15:26:18 CST 2017
     */
    public void setBalance(BigDecimal balance) {
        this.balance = balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.password
     *
     * @return the value of users.password
     *
     * @mbggenerated Fri Mar 17 15:26:18 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.password
     *
     * @param password the value for users.password
     *
     * @mbggenerated Fri Mar 17 15:26:18 CST 2017
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.phone
     *
     * @return the value of users.phone
     *
     * @mbggenerated Fri Mar 17 15:26:18 CST 2017
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.phone
     *
     * @param phone the value for users.phone
     *
     * @mbggenerated Fri Mar 17 15:26:18 CST 2017
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.email
     *
     * @return the value of users.email
     *
     * @mbggenerated Fri Mar 17 15:26:18 CST 2017
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.email
     *
     * @param email the value for users.email
     *
     * @mbggenerated Fri Mar 17 15:26:18 CST 2017
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.school_id
     *
     * @return the value of users.school_id
     *
     * @mbggenerated Fri Mar 17 15:26:18 CST 2017
     */
    public Integer getSchoolId() {
        return schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.school_id
     *
     * @param schoolId the value for users.school_id
     *
     * @mbggenerated Fri Mar 17 15:26:18 CST 2017
     */
    public void setSchoolId(Integer schoolId) {
        this.schoolId = schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.default_addr_id
     *
     * @return the value of users.default_addr_id
     *
     * @mbggenerated Fri Mar 17 15:26:18 CST 2017
     */
    public Integer getDefaultAddrId() {
        return defaultAddrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.default_addr_id
     *
     * @param defaultAddrId the value for users.default_addr_id
     *
     * @mbggenerated Fri Mar 17 15:26:18 CST 2017
     */
    public void setDefaultAddrId(Integer defaultAddrId) {
        this.defaultAddrId = defaultAddrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.openid
     *
     * @return the value of users.openid
     *
     * @mbggenerated Fri Mar 17 15:26:18 CST 2017
     */
    public String getOpenid() {
        return openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.openid
     *
     * @param openid the value for users.openid
     *
     * @mbggenerated Fri Mar 17 15:26:18 CST 2017
     */
    public void setOpenid(String openid) {
        this.openid = openid == null ? null : openid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.photo
     *
     * @return the value of users.photo
     *
     * @mbggenerated Fri Mar 17 15:26:18 CST 2017
     */
    public String getPhoto() {
        return photo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.photo
     *
     * @param photo the value for users.photo
     *
     * @mbggenerated Fri Mar 17 15:26:18 CST 2017
     */
    public void setPhoto(String photo) {
        this.photo = photo == null ? null : photo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.points
     *
     * @return the value of users.points
     *
     * @mbggenerated Fri Mar 17 15:26:18 CST 2017
     */
    public Integer getPoints() {
        return points;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.points
     *
     * @param points the value for users.points
     *
     * @mbggenerated Fri Mar 17 15:26:18 CST 2017
     */
    public void setPoints(Integer points) {
        this.points = points;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.created_at
     *
     * @return the value of users.created_at
     *
     * @mbggenerated Fri Mar 17 15:26:18 CST 2017
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.created_at
     *
     * @param createdAt the value for users.created_at
     *
     * @mbggenerated Fri Mar 17 15:26:18 CST 2017
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.updated_at
     *
     * @return the value of users.updated_at
     *
     * @mbggenerated Fri Mar 17 15:26:18 CST 2017
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.updated_at
     *
     * @param updatedAt the value for users.updated_at
     *
     * @mbggenerated Fri Mar 17 15:26:18 CST 2017
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.deleted_at
     *
     * @return the value of users.deleted_at
     *
     * @mbggenerated Fri Mar 17 15:26:18 CST 2017
     */
    public Date getDeletedAt() {
        return deletedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.deleted_at
     *
     * @param deletedAt the value for users.deleted_at
     *
     * @mbggenerated Fri Mar 17 15:26:18 CST 2017
     */
    public void setDeletedAt(Date deletedAt) {
        this.deletedAt = deletedAt;
    }
}